language: php
sudo: false
dist: xenial
php:
    - '8.0'
    - '8.1'
install:
    - composer install
script:
    - vendor/bin/phpstan --memory-limit=-1 analyse src --level=8
    - vendor/bin/phpunit tests
