version: "3"
services:
    app71:
        build:
            context: .
            dockerfile: ./Dockerfile71
        ports:
            - "8071:80"
        volumes:
            - .:/var/www/html
        environment:
            XDEBUG_EXTENSION_DEBUG: 1
            XDEBUG_CONFIG: "remote_host=172.17.0.1 remote_port=9001 remote_autostart=1"

    app80:
        build:
            context: .
            dockerfile: ./Dockerfile80
        ports:
            - "8080:80"
        volumes:
             - .:/var/www/html
