version: "3"
services:
    app81:
        build:
            context: .
            dockerfile: ./Dockerfile81
        ports:
            - "8081:80"
        volumes:
            - .:/var/www/html
        environment:
            XDEBUG_EXTENSION_DEBUG: 1
            XDEBUG_CONFIG: "remote_host=172.17.0.1 remote_port=9001 remote_autostart=1"
